---
- name: Gather users from the /etc/passwd file.
  shell: | 
    cat /etc/passwd | awk -F":" '{print $1}'
  register: passwd_out
  changed_when: false

- name: Filter fuser accounts.
  set_fact: _items="{{ passwd_out.stdout | regex_findall('^f[0-9][0-9][0-9][0-9][0-9][0-9][0-9]', multiline=True) }}"

- name: Change fuser minimum password age.
  chage: user="{{ item }}" sp_min=1
  with_items: "{{ _items }}"

#- name: Change power broker accounts minimum password age.
#  chage: user="pbpslnx" sp_min=1
#
#- name: Change power broker accounts maximum password age.
#  chage: user="pbpslnx" sp_max=90
