---
- name: "Set iLO credentials - default"
  set_fact:
    ilo_creds_dict: "{{ ilo_creds_dict | default({}) | combine( {item: {'user': vault_default_ilo_user, 'password': vault_default_ilo_password}} ) }}"
  loop: "{{ ilo_creds_server_names }}"
  when:
    - vault_default_ilo_user is defined
    - vault_default_ilo_password is defined
    - cci_hpe_servers[cci_cluster][item].use_default_ilo_creds is defined
    - cci_hpe_servers[cci_cluster][item].use_default_ilo_creds == True or cci_hpe_servers[cci_cluster][item].use_default_ilo_creds == "True" or cci_hpe_servers[cci_cluster][item].use_default_ilo_creds == true or cci_hpe_servers[cci_cluster][item].use_default_ilo_creds == "true"

- name: "Set auto iLO password for cluster - w01-rtm2"
  set_fact:
    auto_ilo_password: "{{ vault_w01_rtm2_auto_ilo_password }}"
  when:
    - cci_cluster == "w01-rtm2"
    - vault_w01_rtm2_auto_ilo_password is defined

- name: "Set auto iLO password for cluster - w01-rtm1"
  set_fact:
    auto_ilo_password: "{{ vault_w01_rtm1_auto_ilo_password }}"
  when:
    - cci_cluster == "w01-rtm1"
    - vault_w01_rtm1_auto_ilo_password is defined

- name: "Set auto iLO password for cluster - w01-asd2"
  set_fact:
    auto_ilo_password: "{{ vault_w01_asd2_auto_ilo_password }}"
  when:
    - cci_cluster == "w01-asd2"
    - vault_w01_asd2_auto_ilo_password is defined

- name: "Set auto iLO password for cluster - w01-zl"
  set_fact:
    auto_ilo_password: "{{ vault_w01_zl_auto_ilo_password }}"
  when:
    - cci_cluster == "w01-zl"
    - vault_w01_zl_auto_ilo_password is defined

- name: "Set auto iLO password for cluster - h01-asd2"
  set_fact:
    auto_ilo_password: "{{ vault_h01_asd2_auto_ilo_password }}"
  when:
    - cci_cluster == "h01-asd2"
    - vault_h01_asd2_auto_ilo_password is defined

- name: "Set auto iLO password for cluster - h01-rtm1"
  set_fact:
    auto_ilo_password: "{{ vault_h01_rtm1_auto_ilo_password }}"
  when:
    - cci_cluster == "h01-rtm1"
    - vault_h01_rtm1_auto_ilo_password is defined

- name: "Set iLO credentials - auto"
  set_fact:
    ilo_creds_dict: "{{ ilo_creds_dict | default({}) | combine( {item: {'user': vault_auto_ilo_user, 'password': auto_ilo_password}} ) }}"
  loop: "{{ ilo_creds_server_names }}"
  when:
    - vault_auto_ilo_user is defined
    - auto_ilo_password is defined
    - cci_hpe_servers[cci_cluster][item].use_default_ilo_creds is not defined
    - not use_default_ilo_creds
