- name: gather some facts
  setup:
    gather_subset:
      - '!all'
      - 'min'

- name: check flask port 5432
  wait_for:
    host: 10.33.8.123
    port: 5432
    state: started
    delay: 0
    timeout: 3
  ignore_errors: yes
  register: port_check

- name: kill existing yum processes
  shell: pkill -9 -f yum
  ignore_errors: yes

- name: install tmc_daemon
  include: install.yaml
  when: port_check['failed'] == false and ansible_distribution_major_version >= '7'
