- name: restart sssd
  service:
    name: sssd
    state: restarted

- name: restart oddjob
  service:
    name: oddjobd
    state: restarted

- name: restart dbus
  service:
    name: dbus
    state: restarted

- name: restart logind
  service:
    name: systemd-logind
    state: restarted

- name: authconfig
  shell: authconfig --update 