- name: "check if /opt/popsplunk/splunkforwarder dir is present"
  stat:
    path: "/opt/popsplunk/splunkforwarder"
  register: popsplunk_splunk
  ignore_errors: true
  changed_when: false

- name: set vars - popsplunk
  set_fact:
    bu_splunk_base_dir: "/opt/popsplunk/splunkforwarder"
    splunk_user: "popsplunk"
  when: popsplunk_splunk.stat.exists

- name: "check if splunk systemd service file exists - 7"
  stat:
    path: "{{ splunk_systemd_service_file }}"
  register: check_splunk_systemd_service_file
  when: ansible_distribution_major_version >= '7'
  ignore_errors: true
  changed_when: false

- name: "check pop splunk user defined in systemd service file - 7"
  shell: "grep User={{ splunk_user }} {{ splunk_systemd_service_file }}"
  register: pop_splunk_systemd_file
  when: ansible_distribution_major_version >= '7' and check_splunk_systemd_service_file.stat.exists
  ignore_errors: true
  changed_when: false

- name: "check if splunk init.d service file exists - 6"
  stat:
    path: "{{ splunk_initd_service_file }}"
  register: check_splunk_initd_service_file
  when: ansible_distribution_major_version == '6'
  ignore_errors: true
  changed_when: false

- name: "check pop splunk base dir defined in initd service file - 6"
  shell: "grep {{ bu_splunk_base_dir }} {{ splunk_initd_service_file }}"
  register: pop_splunk_initd_file
  when: ansible_distribution_major_version == '6' and check_splunk_initd_service_file.stat.exists
  ignore_errors: true
  changed_when: false

- name: "check if splunk is running"
  shell: ps aux | grep -i splunk | grep -v grep
  register: iss_splunk_running
  when: iss_splunk_path.stat.exists or pop_splunk_running is failed

- name: "kill splunk if running"
  shell: "pkill -9 -f splunk"
  register: kill_splunk
  when: iss_splunk_running is success
  ignore_errors: true

- name: "disable boot-start - 7"
  shell: "{{ iss_splunk_base_dir }}/bin/splunk disable boot-start"
  register: disable_boot
  when: ansible_distribution_major_version >= '7' and (iss_splunk_path.stat.exists or pop_splunk_systemd_file is failed or not check_splunk_systemd_service_file.stat.exists)
  ignore_errors: true

- name: "disable boot-start - 6"
  shell: "{{ iss_splunk_base_dir }}/bin/splunk disable boot-start"
  register: disable_boot
  when: ansible_distribution_major_version == '6' and (iss_splunk_path.stat.exists or pop_splunk_initd_file is failed or not check_splunk_initd_service_file.stat.exists)
  ignore_errors: true

- name: remove I&SS SplunkForwarder service symlink - 7
  file:
    path: "/etc/systemd/system/multi-user.target.wants/SplunkForwarder.service"
    state: absent
  ignore_errors: true
  when: ansible_distribution_major_version >= '7' and (iss_splunk_path.stat.exists or pop_splunk_systemd_file is failed or not check_splunk_systemd_service_file.stat.exists)

- name: remove I&SS SplunkForwarder service file - 7
  file:
    path: "/etc/systemd/system/SplunkForwarder.service"
    state: absent
  ignore_errors: true
  when: ansible_distribution_major_version >= '7' and (iss_splunk_path.stat.exists or pop_splunk_systemd_file is failed or not check_splunk_systemd_service_file.stat.exists)

- name: remove I&SS SplunkForwarder service file - 6
  file:
    path: "/etc/init.d/splunk"
    state: absent
  ignore_errors: true
  when: ansible_distribution_major_version == '6' and (iss_splunk_path.stat.exists or pop_splunk_initd_file is failed or not check_splunk_initd_service_file.stat.exists)

- name: remove I&SS splunk install
  yum:
    name: "splunkforwarder"
    state: absent
  when: iss_splunk_path.stat.exists
  ignore_errors: true

- name: remove I&SS splunkforwarder directory
  file:
    path: "{{ iss_splunk_base_dir }}"
    state: absent
  when: iss_splunk_path.stat.exists
  ignore_errors: true

- name: remove I&SS splunk OS ACLs
  acl:
    path: "{{ item }}"
    entry: "user:splunk:r-x"
    state: absent
  with_items:
    - "/var/log"
    - "/var/log/messages"
    - "/var/log/secure"
    - "/var/log/audit/"
    - "/var/log/audit/audit.log"
    - "/var/log/ppp"
    - "/var/log/puppet"
    - "/var/log/samba"
    - "/var/log/sssd"
    - "/var/log/sudo-io"
  ignore_errors: true

- name: remove old POP splunk OS ACLs
  acl:
    path: "{{ item }}"
    entry: "user:{{ splunk_user }}:r-x"
    state: absent
  with_items:
    - "/var/log"
    - "/var/log/messages"
    - "/var/log/secure"
    - "/var/log/audit/"
    - "/var/log/audit/audit.log"
    - "/var/log/ppp"
    - "/var/log/puppet"
    - "/var/log/samba"
    - "/var/log/sssd"
    - "/var/log/sudo-io"
  ignore_errors: true

- name: delete SIEM splunk user
  user:
    name: "splunk"
    state: absent
    remove: true
  ignore_errors: true
